### ISSUE TITLE
[QUESTION] Bluetooth Connectivity

### ISSUE THREAD

**Issue by ShadowEO** [AsteroidOS/asteroid-btsyncd#1]
This is mostly a question born from simple curiosity. I was wondering what would be needed to create a daemon application (say for Ubuntu Touch) that would provide the same function as the Android BTSync application for Asteroid. Would love to try my hand at creating a sync daemon for linux workstations and Ubuntu Touch, but I am unfortunately unsure to where I should begin. What Bluetooth protocols are used, and would it be possible to connect and communicate using a simple Bluez binding for my favorite language? Hell, I'll even take a nice pointing in the right direction as to what part of this and the Android project I should study.

Sorry, I just love how Asteroid is turning out, a little excited to breathe some new life into my G Watch and would like to try my hand working with it.

**Comment by FlorentRevest** [comment]
Hi,

Hopefuly I will find the time to fully document the various Bluetooth Low Energy profiles that are in use but here are a few things you might want to know.

asteroid-btsyncd is a C++ daemon ran on the watch and exposing BLE GATT services thanks to the BlueZ DBus GATT "peripheral" API, this API is unstable but only used on the watch so it shouldn't be an issue for you.

If you want to develop the equivalent of AsteroidOSSync for Ubuntu Touch/SailfishOS/Linux desktops you will need to implement similar features:
* searching and connecting to a BLE device (most of the BlueZ binding should have the necessary methods)
* writing/reading/subscribing to various GATT characteristics (once again, those features are old and the BlueZ API for that has been stable for a while so it shouldn't be an issue to find the necessary features)
* implement the client part of the Notification, Weather, Media and Battery services. (most of them are custom profiles but easy to understand and reproduce)

Start by reading about Bluetooth Low Energy and GATT to understand the various concepts in use, then take a look at the four services implementation, it should give you a good idea of how to develop your daemon.

By the way, if your daemon is generic enough to run on SailfishOS, you could be able to participate in the Maemo.org coding competition https://wiki.maemo.org/Maemo.org_Coding_Competition_2016 and win prizes. (a short description of the Asteroid Sync Client is in the wishlist)

Have a nice day,
    Florent

**Comment by ShadowEO** [comment]
Thanks for the quick reply, this will likely be my first try at an application using PyBluez, so your information there is very helpful. I had been studying the code a little between both the sync daemon and the Android application, both are very readable and I think I should be able to get one started. Unfortunately, I doubt I'd have anything ready for a competition with the schedule my life runs on (it's difficult just finding time to work on my hobby projects), but if anything meaningful comes from my endeavors, I'll be happy to put it up for all to enjoy.

I am hoping to make it rather generic as Ubuntu Touch isn't too specialized itself with the exception of the DE, intercepting libnotify notifications shouldn't be too difficult.

**Comment by FlorentRevest** [comment]
Great, keep us updated!
