### ISSUE TITLE
The screenshot API appears to violate the Bluetooth specification

### ISSUE THREAD

**Issue by beroset** [AsteroidOS/asteroid-btsyncd#21]
# The problem
According to [the current Bluetooth core specification](https://www.bluetooth.com/specifications/specs/core-specification/), in Volume 3, Part F, section 3.2.9, it says:
> The maximum length of an attribute value shall be 512 octets.
>
Since a screenshot is typically many kilobytes, our API does not appear to conform.  At the moment, we have two characteristics:
> Screenshot Service (UUID: 00006071-0000-0000-0000-00A57E401D05)
>
>Screenshot Request Characteristic (UUID: 00006001-0000-0000-0000-00A57E401D05)
>
>This characteristic can be written by the client to any value (for example one byte set to 0) to trigger a byte stream on the Screenshot Content Characteristic.
>
>Screenshot Content Characteristic (UUID: 00006002-0000-0000-0000-00A57E401D05)
>
>This characteristic can be used to be notified of a screenshot content. After a write to the Screenshot Request Characteristic, the first value signaled by the Screenshot Content Characteristic should be made of four bytes containing the size of the data to be transmitted and can be used to show a progress bar during the screenshot download time. The rest of the transmission is made of chunks of raw data to be concatenated by the client in a buffer to reconstruct a screenshot of the watch's screen. The complete buffer should be a valid JPEG file but other formats could also be considered in the future.

While the request characteristic is fine, the Content is *always* going to be bigger than 512 bytes.  I think the way to handle this is to change the API to use multiple characteristics.  

# Proposed new API

1. Request - initiate a request for a screenshot (as it is now)
2. Size  - 4-byte value representing the size of the most recently captured screenshot (or 0 if none)
3. Chunk Offset - the offset in bytes to the beginning of a chunk 
4. Chunk Content - contains the chunk corresponding to the Chunk Offset

If each Chunk were a fixed 16 bytes long, this would allow a 4-byte offset to be communicated with each chunk.

Reading a Chunk Content with a Chunk Offset outside the range indicated by size would simply return zero bytes (not even including an offset).  Reading a Chunk Content that was a last partial Chunk (e.g. the end of the file) would return a valid Chunk but with only as many bytes as actually exist to the end of the file.

## Potential drawbacks

- If a new screenshot were requested before the last one was entirely retrieved, there is nothing in the proposed API that would indicate that this had happened.
- Getting a screenshot would take more overhead than the existing scheme
- No integrity checking.  The proposed API doesn't include a CRC or cryptographic hash to allow the receiver to validate that the screenshot was correctly received.  We could add one, or perhaps make it part of the Size characteristic.

## Potential advantages

- The updated spec would conform to Bluetooth specifications
- The mechanism may be more reliable (reliability problems with the existing implementations were what led me to investigate this)
- Even devices implementing older specifications should be able to use this API

**Comment by FlorentRevest** [comment]
> The maximum length of an attribute value shall be 512 octets.

If I'm not mistaken (it's been a while, I could be wrong) each individual reads of the attribute is actually <= 512B.

That being said, I very much agree that the current API sucks.

> 1. Request - initiate a request for a screenshot (as it is now)
> 2. Size - 4-byte value representing the size of the most recently captured screenshot (or 0 if none)
> 3. Chunk Offset - the offset in bytes to the beginning of a chunk
> 4. Chunk Content - contains the chunk corresponding to the Chunk Offset

And this would be a strong improvement already :) 

> - If a new screenshot were requested before the last one was entirely retrieved, there is nothing in the proposed API that would indicate that this had happened.

Only one device can be paired to the watch so we don't need to think too hard about concurrency. The companion app should have all the context to know when it requests a screenshot and whether it got the full reply or not. If the companion app on that device is dumb enough to do what you describe, too bad. :p 

> Getting a screenshot would take more overhead than the existing scheme

This is not a performance critical operation, the user can wait a few more seconds for a screenshot :) 

> No integrity checking. The proposed API doesn't include a CRC or cryptographic hash to allow the receiver to validate that the screenshot was correctly received. We could add one, or perhaps make it part of the Size characteristic.

It would be interesting to check whether the lower level BLE protocol has integrity guarantees. My guess is that integrity isn't really an issue here. If we are able to read the full byte array length it's probably good enough.



So yeah, overall I'd approve this change, this would be a step in the right direction
